// Bilingual dictionary for Egy Cleans (English + العربية).
// Access via store.t['key']; list values via (store.t['ct'] as List).

const Map<String, dynamic> _en = {
  'appName': 'Egy Cleans', 'tagline': 'Trusted home cleaning, on demand.', 'city': 'Cairo, Egypt', 'searchPh': 'What service do you need today?',
  'welcomeBack': 'Welcome back', 'loginSub': 'Log in to book trusted cleaners.', 'signupSub': 'Join Egy Cleans in under a minute.',
  'individual': 'Individual', 'corporate': 'Corporate', 'email': 'Email', 'password': 'Password', 'login': 'Log in', 'createAccount': 'Create account',
  'noAccount': "Don't have an account?", 'haveAccount': 'Already have an account?', 'mobileNumber': 'Mobile number', 'supportNumber': 'Support number', 'supportPh': 'Customer support line',
  'corpRegTitle': 'Register your company', 'corpRegSub': 'Upload your documents for verification. Approval usually takes 1–2 business days.',
  'companyName': 'Company name', 'companyNamePh': 'e.g. Sparkle Masr Cleaning', 'tradeLicence': 'Trade licence', 'ownerId': 'Owner / manager ID', 'tapUpload': 'Tap to upload', 'uploaded': 'Uploaded', 'submitReview': 'Submit for review',
  'reviewTitle': 'Under review', 'reviewBody': 'Thanks! Your company is being verified. You can log in now, but booking access unlocks once approved.', 'reviewNote': 'We verify the trade licence and owner ID to keep the marketplace safe for customers.', 'simulateApprove': 'Simulate approval (demo)', 'continueLimited': 'Continue with limited access', 'limitedNote': 'Booking access unlocks after approval.',
  'km': 'km', 'reviews': 'reviews', 'from': 'from', 'perHour': '/hr', 'perHourShort': ' /hr', 'bookNow': 'Book now', 'viewAll': 'View all',
  'navHome': 'Home', 'navSearch': 'Search', 'navBookings': 'Bookings', 'navProfile': 'Profile',
  'navDashboard': 'Dashboard', 'navServices': 'Services', 'navHistory': 'History', 'navAlerts': 'Alerts',
  'greeting': 'Good morning', 'userName': 'Rana', 'walletBalance': 'Wallet balance', 'quickBook': 'Book', 'upcoming': 'Upcoming', 'upcomingBadge': 'Upcoming', 'recent': 'Recent', 'services': 'Services', 'topRated': 'Top rated near you',
  'searchTitle': 'Find a cleaner', 'results': 'results found', 'experience': 'Experience', 'fromPrice': 'From', 'yrs': 'yrs', 'coverage': 'Coverage area', 'gallery': 'Gallery',
  'account': 'Account', 'wallet': 'Wallet', 'addCard': 'Add payment card', 'expires': 'Expires', 'settings': 'Settings', 'personalDetails': 'Personal details', 'language': 'Language', 'appearance': 'Appearance', 'help': 'Help & support', 'logout': 'Log out',
  'step': 'Step', 'configTitle': 'Build your booking', 'cleaningType': 'CLEANING TYPE', 'propertyType': 'PROPERTY TYPE', 'hours': 'Hours', 'cleanersUnit': 'Cleaners', 'suppliesQ': 'Bring cleaning supplies', 'scheduleTitle': 'When & where', 'pickDate': 'PICK A DATE', 'pickTime': 'PICK A TIME', 'addr': 'ADDRESS', 'useLocation': 'Use my current location', 'mapsPlaceholder': 'Google Maps', 'addressPh': 'Street, building, area', 'notesK': 'NOTES', 'notesPh': 'Any special instructions…',
  'summary': 'Booking summary', 'details': 'Booking details', 'priceBreakdown': 'Price breakdown', 'labour': 'Labour', 'supplies': 'Supplies', 'subtotal': 'Subtotal', 'platformFee': 'Platform fee (5%)', 'vat': 'VAT (14%)', 'total': 'Total', 'cancelTitle': 'Free cancellation up to 12h before', 'cancelBody': 'I agree to the cancellation policy and terms of service.', 'continuePay': 'Continue to payment',
  'payment': 'Payment', 'choosePay': 'Choose payment method', 'pay': 'Pay',
  'paySuccess': 'Payment successful', 'bookingRequested': 'Booking requested', 'bookingConfirmed': 'Your booking is confirmed 🎉', 'amountPaid': 'Amount', 'invoice': 'Invoice', 'share': 'Share', 'viewBookings': 'View my bookings',
  'myBookings': 'My bookings', 'past': 'Past', 'confirmed': 'Confirmed', 'completed': 'Completed', 'emptyUpTitle': 'No upcoming bookings', 'emptyPastTitle': 'No past bookings', 'emptyBody': 'Book a cleaning and it will appear here.', 'browse': 'Browse companies', 'continue': 'Continue', 'review': 'Review', 'estTotal': 'Estimated total',
  'dateTime': 'Date & time', 'service': 'Service', 'property': 'Property', 'cleanersK': 'Cleaners', 'notesRow': 'Notes', 'none': '—',
  'todayBookings': "Today's jobs", 'earnings': 'Earnings (mo)', 'incoming': 'Incoming bookings', 'pending': 'pending', 'approve': 'Approve', 'decline': 'Decline', 'acknowledge': 'Acknowledge', 'inProcess': 'In process', 'cash': 'Cash', 'paid': 'Paid', 'acked': 'Acknowledged',
  'manageServices': 'My services', 'servicesSub': 'Set your cleaning types, rates and capacity.', 'addService': 'Add', 'cleanersAvail': 'cleaners', 'capacity': 'up to', 'areaCovered': 'Coverage & capacity', 'customerHistory': 'Customer bookings', 'notifications': 'Notifications', 'needsApproval': 'Needs your approval', 'newBookingCash': 'New cash booking', 'newBookingPaid': 'New paid booking',
  'editContacts': 'Editable contacts', 'managerContact': 'Manager contact', 'supportContact': 'Support contact', 'save': 'Save changes', 'saved': 'Saved ✓', 'verifiedDocs': 'Verified documents', 'locked': 'Locked', 'cannotEditDocs': 'Trade licence and owner details are locked after verification. Contact support to change them.', 'approved': 'Verified partner', 'pendingReview': 'Under review',
  'months': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  'days': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  'ct': ['Standard', 'Deep clean', 'Move in / out', 'Sofa & carpet', 'Post-construction'],
  'cts': ['General tidy', 'Top-to-bottom', 'Empty-home reset', 'Upholstery', 'After renovation'],
  'pt': ['Studio', '1 Bedroom', '2 Bedroom', '3 Bedroom', 'Duplex', 'Villa'],
  'pm': ['Base', 'Base', '+20%', '+40%', '+60%', '+80%'],
  'pay0': ['Credit / Debit card', 'Visa · Mastercard'], 'pay1': ['Apple Pay', 'Touch / Face ID'], 'pay2': ['Google Pay', 'Fast checkout'], 'pay3': ['Meeza', 'National card'], 'pay4': ['Vodafone Cash', 'Mobile wallet'], 'pay5': ['InstaPay', 'Bank transfer'], 'pay6': ['Cash on arrival', 'Pay the cleaner'],
  'instr': ['Focus on kitchen', 'Eco products', 'Pet-friendly', 'Bring a ladder', 'Balcony'],
  // eased-login additions
  'quickAccess': 'Quick access', 'demoHint': 'Demo credentials are pre-filled — just continue.', 'continueWord': 'Continue', 'orWord': 'or', 'enterAsCustomer': 'Enter as customer', 'enterAsCompany': 'Enter as company',
};

const Map<String, dynamic> _ar = {
  'appName': 'إيجي كلينز', 'tagline': 'تنظيف منزلي موثوق، عند الطلب.', 'city': 'القاهرة، مصر', 'searchPh': 'ما الخدمة التي تحتاجها اليوم؟',
  'welcomeBack': 'مرحباً بعودتك', 'loginSub': 'سجّل الدخول لحجز عمال نظافة موثوقين.', 'signupSub': 'انضم إلى إيجي كلينز في أقل من دقيقة.',
  'individual': 'فرد', 'corporate': 'شركة', 'email': 'البريد الإلكتروني', 'password': 'كلمة المرور', 'login': 'تسجيل الدخول', 'createAccount': 'إنشاء حساب',
  'noAccount': 'ليس لديك حساب؟', 'haveAccount': 'لديك حساب بالفعل؟', 'mobileNumber': 'رقم الموبايل', 'supportNumber': 'رقم الدعم', 'supportPh': 'خط دعم العملاء',
  'corpRegTitle': 'سجّل شركتك', 'corpRegSub': 'ارفع مستنداتك للتحقق. تستغرق الموافقة عادةً من ١ إلى ٢ يوم عمل.',
  'companyName': 'اسم الشركة', 'companyNamePh': 'مثال: سباركل مصر للتنظيف', 'tradeLicence': 'السجل التجاري', 'ownerId': 'بطاقة المالك / المدير', 'tapUpload': 'اضغط للرفع', 'uploaded': 'تم الرفع', 'submitReview': 'إرسال للمراجعة',
  'reviewTitle': 'قيد المراجعة', 'reviewBody': 'شكراً! يتم التحقق من شركتك. يمكنك تسجيل الدخول الآن، لكن الحجز يُفتح بعد الموافقة.', 'reviewNote': 'نتحقق من السجل التجاري وبطاقة المالك للحفاظ على أمان المنصة للعملاء.', 'simulateApprove': 'محاكاة الموافقة (تجريبي)', 'continueLimited': 'المتابعة بصلاحية محدودة', 'limitedNote': 'يُفتح الحجز بعد الموافقة.',
  'km': 'كم', 'reviews': 'تقييم', 'from': 'من', 'perHour': '/ساعة', 'perHourShort': ' /ساعة', 'bookNow': 'احجز الآن', 'viewAll': 'عرض الكل',
  'navHome': 'الرئيسية', 'navSearch': 'بحث', 'navBookings': 'حجوزاتي', 'navProfile': 'حسابي',
  'navDashboard': 'لوحة', 'navServices': 'خدماتي', 'navHistory': 'السجل', 'navAlerts': 'تنبيهات',
  'greeting': 'صباح الخير', 'userName': 'رنا', 'walletBalance': 'رصيد المحفظة', 'quickBook': 'احجز', 'upcoming': 'القادمة', 'upcomingBadge': 'قادم', 'recent': 'الأخيرة', 'services': 'الخدمات', 'topRated': 'الأعلى تقييماً بالقرب منك',
  'searchTitle': 'ابحث عن عامل نظافة', 'results': 'نتيجة', 'experience': 'الخبرة', 'fromPrice': 'يبدأ من', 'yrs': 'سنوات', 'coverage': 'منطقة التغطية', 'gallery': 'معرض الصور',
  'account': 'الحساب', 'wallet': 'المحفظة', 'addCard': 'إضافة بطاقة دفع', 'expires': 'تنتهي', 'settings': 'الإعدادات', 'personalDetails': 'البيانات الشخصية', 'language': 'اللغة', 'appearance': 'المظهر', 'help': 'المساعدة والدعم', 'logout': 'تسجيل الخروج',
  'step': 'خطوة', 'configTitle': 'جهّز حجزك', 'cleaningType': 'نوع التنظيف', 'propertyType': 'نوع العقار', 'hours': 'ساعات', 'cleanersUnit': 'العمال', 'suppliesQ': 'إحضار مستلزمات التنظيف', 'scheduleTitle': 'متى وأين', 'pickDate': 'اختر التاريخ', 'pickTime': 'اختر الوقت', 'addr': 'العنوان', 'useLocation': 'استخدم موقعي الحالي', 'mapsPlaceholder': 'خرائط جوجل', 'addressPh': 'الشارع، المبنى، المنطقة', 'notesK': 'ملاحظات', 'notesPh': 'أي تعليمات خاصة…',
  'summary': 'ملخص الحجز', 'details': 'تفاصيل الحجز', 'priceBreakdown': 'تفاصيل السعر', 'labour': 'العمالة', 'supplies': 'المستلزمات', 'subtotal': 'المجموع الفرعي', 'platformFee': 'رسوم المنصة (٥٪)', 'vat': 'ضريبة القيمة المضافة (١٤٪)', 'total': 'الإجمالي', 'cancelTitle': 'إلغاء مجاني حتى ١٢ ساعة قبل الموعد', 'cancelBody': 'أوافق على سياسة الإلغاء وشروط الخدمة.', 'continuePay': 'المتابعة للدفع',
  'payment': 'الدفع', 'choosePay': 'اختر وسيلة الدفع', 'pay': 'ادفع',
  'paySuccess': 'تم الدفع بنجاح', 'bookingRequested': 'تم إرسال الطلب', 'bookingConfirmed': 'تم تأكيد حجزك 🎉', 'amountPaid': 'المبلغ', 'invoice': 'الفاتورة', 'share': 'مشاركة', 'viewBookings': 'عرض حجوزاتي',
  'myBookings': 'حجوزاتي', 'past': 'السابقة', 'confirmed': 'مؤكد', 'completed': 'مكتمل', 'emptyUpTitle': 'لا حجوزات قادمة', 'emptyPastTitle': 'لا حجوزات سابقة', 'emptyBody': 'احجز خدمة تنظيف وستظهر هنا.', 'browse': 'تصفح الشركات', 'continue': 'متابعة', 'review': 'مراجعة', 'estTotal': 'الإجمالي التقديري',
  'dateTime': 'التاريخ والوقت', 'service': 'الخدمة', 'property': 'نوع العقار', 'cleanersK': 'عدد العمال', 'notesRow': 'ملاحظات', 'none': '—',
  'todayBookings': 'مهام اليوم', 'earnings': 'الأرباح (شهر)', 'incoming': 'حجوزات واردة', 'pending': 'بانتظار', 'approve': 'قبول', 'decline': 'رفض', 'acknowledge': 'تأكيد الاستلام', 'inProcess': 'قيد التنفيذ', 'cash': 'كاش', 'paid': 'مدفوع', 'acked': 'تم التأكيد',
  'manageServices': 'خدماتي', 'servicesSub': 'حدّد أنواع التنظيف والأسعار والسعة.', 'addService': 'إضافة', 'cleanersAvail': 'عمال', 'capacity': 'حتى', 'areaCovered': 'التغطية والسعة', 'customerHistory': 'حجوزات العملاء', 'notifications': 'الإشعارات', 'needsApproval': 'يحتاج موافقتك', 'newBookingCash': 'حجز كاش جديد', 'newBookingPaid': 'حجز مدفوع جديد',
  'editContacts': 'جهات اتصال قابلة للتعديل', 'managerContact': 'اتصال المدير', 'supportContact': 'اتصال الدعم', 'save': 'حفظ التغييرات', 'saved': 'تم الحفظ ✓', 'verifiedDocs': 'المستندات الموثقة', 'locked': 'مقفل', 'cannotEditDocs': 'السجل التجاري وبيانات المالك مقفلة بعد التحقق. تواصل مع الدعم لتغييرها.', 'approved': 'شريك موثّق', 'pendingReview': 'قيد المراجعة',
  'months': ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
  'days': ['أحد', 'إثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'سبت'],
  'ct': ['عادي', 'تنظيف عميق', 'انتقال سكن', 'كنب وسجاد', 'بعد التشطيب'],
  'cts': ['ترتيب عام', 'تنظيف شامل', 'تجهيز منزل فارغ', 'مفروشات', 'بعد الترميم'],
  'pt': ['استوديو', 'غرفة نوم', 'غرفتا نوم', '٣ غرف نوم', 'دوبلكس', 'فيلا'],
  'pm': ['أساسي', 'أساسي', '+٢٠٪', '+٤٠٪', '+٦٠٪', '+٨٠٪'],
  'pay0': ['بطاقة ائتمان / خصم', 'فيزا · ماستركارد'], 'pay1': ['Apple Pay', 'بصمة / وجه'], 'pay2': ['Google Pay', 'دفع سريع'], 'pay3': ['ميزة', 'البطاقة الوطنية'], 'pay4': ['فودافون كاش', 'محفظة موبايل'], 'pay5': ['إنستاباي', 'تحويل بنكي'], 'pay6': ['الدفع عند الوصول', 'ادفع للعامل'],
  'instr': ['التركيز على المطبخ', 'منتجات صديقة للبيئة', 'مناسب للحيوانات', 'إحضار سلّم', 'البلكونة'],
  'quickAccess': 'دخول سريع', 'demoHint': 'بيانات الدخول التجريبية مُعبّأة — فقط تابِع.', 'continueWord': 'متابعة', 'orWord': 'أو', 'enterAsCustomer': 'الدخول كعميل', 'enterAsCompany': 'الدخول كشركة',
};

Map<String, dynamic> stringsFor(String lang) => lang == 'ar' ? _ar : _en;
